version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taller_challenge_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taller_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./migrations:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: taller_challenge_network
